### ISSUE TITLE
MTU values don't seem to be right, somewhere

### ISSUE THREAD

**Issue by robotman3000** [JRakNet/JRakNet#24]
When connecting to a Minecraft PE server it sends back a connection response 1 packet with an MTU of 1492, while the library expects an MTU of 1464. It then throws this exception:

`net.marfgamer.jraknet.client.InvalidProtocolException: Received invalid packet from server during login
	at net.marfgamer.jraknet.client.SessionPreparation.handlePacket(SessionPreparation.java:94)
	at net.marfgamer.jraknet.client.RakNetClient.handleMessage(RakNetClient.java:410)
	at net.marfgamer.jraknet.client.RakNetClientHandler.channelRead(RakNetClientHandler.java:67)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:956)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)`

The servers I've tried are MiNet and an MCPE Lan Game. I've also tried Nukkit, but haven't verified if the problem is the same. I got this stack trace when I modified `cn.nukkit.raknet.server.SessionManager.tickProcessor()` to print the exception before blocking an address

`2017-1-24 21:38:44 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 17
	at cn.nukkit.raknet.protocol.Packet.getByte(Packet.java:71)
	at cn.nukkit.raknet.protocol.packet.CLIENT_CONNECT_DataPacket.decode(CLIENT_CONNECT_DataPacket.java:34)
	at cn.nukkit.raknet.server.Session.handleEncapsulatedPacketRoute(Session.java:387)
	at cn.nukkit.raknet.server.Session.handleEncapsulatedPacket(Session.java:335)
	at cn.nukkit.raknet.server.Session.handlePacket(Session.java:491)
	at cn.nukkit.raknet.server.SessionManager.receivePacket(SessionManager.java:183)
	at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:80)
	at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
	at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
	at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)`

I can't figure out where the problem is, but that's what I do know.

**Comment by whirvis** [comment]
Could I see the code that you are using that triggers this? The invalid packet should only be thrown if a packet is received out of order or fails to decode. Also, are you using the latest version of JRakNet (Version 2.2.5)?

Also, the reason this exception is being thrown is because the client has a set MTU, but in the connection process the server is returning a bigger MTU than the client says it can handle. I might be implementing the protocol wrong and might be misunderstanding how the client and server work with that value. But, I will look more into tonight and add more detailed exception messages for client login failures for the next version :)

**Comment by robotman3000** [comment]
I am using version 2.4.5 of the library. The exception is being thrown after calling connect(ip, port) with an instance of RakNetClient. There isn't all that much code to see (just a try/catch with that call), but if there is something specific you are looking for, let me know.

**Comment by whirvis** [comment]
I have updated the client to now give more informative messages, but I think the problem is that I am interpreting the MTU data wrong.

**Comment by whirvis** [comment]
I seemed to have pinned down the error, Nukkit is looking for a byte in the ConnectionRequest packet (AKA the 0x09 or CLIENT_CONNECT_DataPacket) that is seeing if security is enabled. JRakNet did not have this byte being written, I added it and it should be fixed now :)

New version 2.4.6 will have this fix, be sure to download it!
