### ISSUE TITLE
java.lang.UnsupportedOperationException: direct buffer

### ISSUE THREAD

**Issue by MrPowerGamerBR** [JRakNet/JRakNet#29]
```
fev 21, 2017 8:54:10 PM io.netty.channel.AbstractChannelHandlerContext invokeExceptionCaught
ADVERT╩NCIA: An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.UnsupportedOperationException: direct buffer
        at io.netty.buffer.PooledUnsafeDirectByteBuf.array(PooledUnsafeDirectByteBuf.java:343)
        at net.marfgamer.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:332)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1319)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:904)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:805)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at java.lang.Thread.run(Unknown Source)
```

Latest JRakNet version

Code:
```

        raknet = new RakNetServer(server.getPort(), server.getMaxPlayers(), new MCPEIdentifier(server.getMotd(), ProtocolInfo.CURRENT_PROTOCOL, ProtocolInfo.MINECRAFT_VERSION_NETWORK, server.getOnlinePlayers().size(),
                server.getMaxPlayers(), server.getServerUniqueId().getMostSignificantBits() & Long.MAX_VALUE, "New World", "Survival"));
        raknet.setListener(new RakNetServerListener() {
            // Client connected
            @Override
            public void onClientConnect(RakNetClientSession session) {
                openSession(String.valueOf(session.getGloballyUniqueId()), session.getAddress().getHostString(), session.getInetPort(), session.getGloballyUniqueId());
            }

            // Client disconnected
            @Override
            public void onClientDisconnect(RakNetClientSession session, String reason) {
                // We first check if the global ID exists (prevents NPE when shutting down the server)
                if (players.containsKey(String.valueOf(session.getGloballyUniqueId()))) {
                    close(players.get(String.valueOf(session.getGloballyUniqueId())), reason);
                }
            }

            // Packet received
            @Override
            public void handleMessage(RakNetClientSession session, RakNetPacket packet, int channel) {
                handleRakNetPacket(session.getGloballyUniqueId(), packet);
            }
            
            // UT3 server query
            @Override
            public void handleNettyMessage(ByteBuf buf, InetSocketAddress address) {
                System.out.println("Received Netty message!");
            }
        });
```

(This happens without any clients connecting to it)

**Comment by whirvis** [comment]
You're fast!

**Comment by MrPowerGamerBR** [comment]
@MarfGamer You're fast!²

**Comment by whirvis** [comment]
I repushed the code on the same version, run the code again to make sure it's fixed :)

**Comment by MrPowerGamerBR** [comment]
@MarfGamer is the version at your maven repo already updated with this fix?

**Comment by whirvis** [comment]
Yep! I simply repushed the fixed code as the same version since you found it literally less than a minute after I had pushed it. To make sure maven is using the right code, go to your .m2 folder and navigate to the JRakNet jar and delete it for the current version :)

**Comment by MrPowerGamerBR** [comment]
![http://i.imgur.com/WPIYhjk.png](http://i.imgur.com/WPIYhjk.png) Come on Eclipse...

**Comment by whirvis** [comment]
Refresh it using F5. If that doesn't work, relaunch eclipse entirely

**Comment by whirvis** [comment]
Also let me know when if it's fixed :)

**Comment by MrPowerGamerBR** [comment]
@MarfGamer fixed 👍

**Comment by whirvis** [comment]
Alright, great! I was trying to make it so the buffer was copied instead of it using the same one. However, I think it'll be fine if I leave it so the same buffer is used. This will help prevent people from trying to read data that's meant to be used by the server only :P

**Comment by MrPowerGamerBR** [comment]
@MarfGamer also, I'm not sure if I'm doing something wrong but...

```
            // UT3 server query
            @Override
            public void handleNettyMessage(ByteBuf buf, InetSocketAddress address) {
                System.out.println("Received Netty message!");
            }
```

This should send "Received Netty message!" in the console every time a packet is received, right? Because for me that message is never shown in the console (even if I try to use mcapi to query nothing is shown in the console)

**Comment by whirvis** [comment]
Oh god I think I broke something. Are you able to connect to the server still? And is the MOTD still showing up in the player list?

**Comment by MrPowerGamerBR** [comment]
@MarfGamer 
![http://i.imgur.com/tTl77t6.png](http://i.imgur.com/tTl77t6.png)
![http://i.imgur.com/YAPNtlc.png](http://i.imgur.com/YAPNtlc.png)

**Comment by whirvis** [comment]
Ok so everything is still working?

**Comment by MrPowerGamerBR** [comment]
@MarfGamer yeah, except the handleNettyMessage. (because it is never triggered)

**Comment by whirvis** [comment]
Ok, that's odd. I got really worried because for me MOTD's stopped showing up in the game for me. I'll test this real quick

**Comment by whirvis** [comment]
That's weird, the method is working for me. Could I see your class code?

**Comment by MrPowerGamerBR** [comment]
@MarfGamer 

```
package cn.nukkit.network;

import cn.nukkit.Nukkit;
import cn.nukkit.Player;
import cn.nukkit.Server;
import cn.nukkit.event.player.PlayerCreationEvent;
import cn.nukkit.event.server.QueryRegenerateEvent;
import cn.nukkit.network.protocol.DataPacket;
import cn.nukkit.network.protocol.ProtocolInfo;
import cn.nukkit.raknet.protocol.EncapsulatedPacket;
import cn.nukkit.raknet.protocol.packet.PING_DataPacket;
import cn.nukkit.utils.Binary;
import cn.nukkit.utils.MainLogger;
import io.netty.buffer.ByteBuf;
import net.marfgamer.jraknet.RakNetPacket;
import net.marfgamer.jraknet.identifier.MCPEIdentifier;
import net.marfgamer.jraknet.protocol.Reliability;
import net.marfgamer.jraknet.server.RakNetServer;
import net.marfgamer.jraknet.server.RakNetServerListener;
import net.marfgamer.jraknet.server.ServerPing;
import net.marfgamer.jraknet.session.RakNetClientSession;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.UnknownHostException;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * author: MagicDroidX
 * Nukkit Project
 */
public class RakNetInterface implements AdvancedSourceInterface {

    private final Server server;

    private Network network;

    private final RakNetServer raknet;

    private final Map<String, Player> players = new ConcurrentHashMap<>();

    private final Map<Integer, String> identifiers = new ConcurrentHashMap<>();

    private final Map<String, Integer> identifiersACK = new ConcurrentHashMap<>();

    private int[] channelCounts = new int[256];

    public RakNetInterface(Server server) {
        this.server = server;

        raknet = new RakNetServer(server.getPort(), server.getMaxPlayers(), new MCPEIdentifier(server.getMotd(), ProtocolInfo.CURRENT_PROTOCOL, ProtocolInfo.MINECRAFT_VERSION_NETWORK, server.getOnlinePlayers().size(),
                server.getMaxPlayers(), server.getServerUniqueId().getMostSignificantBits() & Long.MAX_VALUE, "New World", "Survival"));
        raknet.setListener(new RakNetServerListener() {
            // Client connected
            @Override
            public void onClientConnect(RakNetClientSession session) {
                openSession(String.valueOf(session.getGloballyUniqueId()), session.getAddress().getHostString(), session.getInetPort(), session.getGloballyUniqueId());
            }

            // Client disconnected
            @Override
            public void onClientDisconnect(RakNetClientSession session, String reason) {
                // We first check if the global ID exists (prevents NPE when shutting down the server)
                if (players.containsKey(String.valueOf(session.getGloballyUniqueId()))) {
                    close(players.get(String.valueOf(session.getGloballyUniqueId())), reason);
                }
            }

            // Packet received
            @Override
            public void handlePacket(RakNetClientSession session, RakNetPacket packet, int channel) {
                handleRakNetPacket(session.getGloballyUniqueId(), packet);
            }
            
            // UT3 server query
            @Override
            public void handleNettyMessage(ByteBuf buf, InetSocketAddress address) {
                System.out.println("Received Netty message!");
            }
        });

        // Start server
        raknet.startThreaded();
    }

    @Override
    public void setNetwork(Network network) {
        this.network = network;
    }

    @Override
    public boolean process() {
        boolean work = false;
        return work;
    }

    public void closeSession(String identifier, String reason) {
        if (this.players.containsKey(identifier)) {
            Player player = this.players.get(identifier);
            this.identifiers.remove(player.rawHashCode());
            this.players.remove(identifier);
            this.identifiersACK.remove(identifier);
            player.close(player.getLeaveMessage(), reason);
        }
    }

    @Override
    public long getNetworkLatency(Player player) {
        return this.raknet.getSession(player.globalRakNetId).getLatency();
    }

    @Override
    public void close(Player player) {
        this.close(player, "unknown reason");
    }

    @Override
    public void close(Player player, String reason) {
        if (this.identifiers.containsKey(player.rawHashCode())) {
            String id = this.identifiers.get(player.rawHashCode());
            // TODO: I don't know WHY they did this for no reason at all!
            // Those things will be closed in #closeSession anyway
            // this.players.remove(id);
            // this.networkLatency.remove(id);
            // this.identifiersACK.remove(id);
            this.closeSession(id, reason);
            // this.identifiers.remove(player.rawHashCode());
        }
    }

    @Override
    public void shutdown() {
        this.raknet.shutdown();
    }

    @Override
    public void emergencyShutdown() {
        // TODO: What is a "emergency shutdown"?
        this.raknet.shutdown();
    }

    public void openSession(String identifier, String address, int port, long clientID) {
        PlayerCreationEvent ev = new PlayerCreationEvent(this, Player.class, Player.class, null, address, port);
        this.server.getPluginManager().callEvent(ev);
        Class<? extends Player> clazz = ev.getPlayerClass();

        try {
            Constructor constructor = clazz.getConstructor(SourceInterface.class, Long.class, String.class, int.class);
            Player player = (Player) constructor.newInstance(this, ev.getClientId(), ev.getAddress(), ev.getPort());
            player.globalRakNetId = clientID;
            this.players.put(identifier, player);
            this.identifiersACK.put(identifier, 0);
            this.identifiers.put(player.rawHashCode(), identifier);
            this.server.addPlayer(identifier, player);
        } catch (NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            Server.getInstance().getLogger().logException(e);
        }
    }

    public void handleRakNetPacket(long identifier, RakNetPacket packet) {
        if (this.players.containsKey(String.valueOf(identifier))) {
            DataPacket pk = null;
            try {
                if (packet.array().length > 0) {
                    pk = this.getPacket(packet.array());
                    if (pk != null) {
                        pk.decode();
                        DataPacket finalPk = pk;
                        // Synchronize the data processing to the main thread
                        // *Maybe* we don't need to synchronize it, but as Nukkit isn't thread safe...
                        // better safe than sorry
                        Server.getInstance().getScheduler().scheduleTask(new Runnable() {
                            public void run() {
                                players.get(String.valueOf(identifier)).handleDataPacket(finalPk);
                            }
                        });
                    }
                }
            } catch (Exception e) {
                this.server.getLogger().logException(e);
                if (Nukkit.DEBUG > 1 && pk != null) {
                    MainLogger logger = this.server.getLogger();
                    //                    if (logger != null) {
                    logger.debug("Packet " + pk.getClass().getName() + " 0x" + Binary.bytesToHexString(packet.array()));
                    //logger.logException(e);
                    //                    }
                }

                if (this.players.containsKey(String.valueOf(identifier))) {
                    try {
                        this.raknet.blockAddress(InetAddress.getByName(this.players.get(identifier).getAddress()), 5);
                    } catch (UnknownHostException e1) {
                        e1.printStackTrace();
                    }
                }
            }
        }
    }

    public void handleEncapsulated(String identifier, EncapsulatedPacket packet, int flags) {
        throw new RuntimeException();
    }

    @Override
    public void blockAddress(String address) {
        this.blockAddress(address, 300);
    }

    @Override
    public void blockAddress(String address, int timeout) {
        try {
            this.raknet.blockAddress(InetAddress.getByName(address), timeout);
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }
    }

    public void handleRaw(String address, int port, byte[] payload) {
        this.server.handlePacket(address, port, payload);
    }

    @Override
    public void sendRawPacket(String address, int port, byte[] payload) {
        byte[] buffer = Binary.appendBytes(
                new byte[]{(byte) (address.length() & 0xff)},
                address.getBytes(StandardCharsets.UTF_8),
                Binary.writeShort(port),
                payload
                );
        RakNetPacket pk = new RakNetPacket(0x8);
        pk.write(buffer);
        // raknet.sendRawMessage(pk, InetSocketAddress.createUnresolved(address, port)); // Sends the raw bytes from the packet to the specified address
    }

    public void notifyACK(String identifier, int identifierACK) {
        // TODO: Better ACK notification implementation!
        for (Player p : server.getOnlinePlayers().values()) {
            p.notifyACK(identifierACK);
        }
    }

    @Override
    public void setName(String name) {
        QueryRegenerateEvent info = this.server.getQueryInformation();

        raknet.setIdentifier(new MCPEIdentifier(server.getMotd(), ProtocolInfo.CURRENT_PROTOCOL, ProtocolInfo.MINECRAFT_VERSION_NETWORK, info.getPlayerCount(),
                info.getMaxPlayerCount(), server.getServerUniqueId().getMostSignificantBits() & Long.MAX_VALUE, "New World", "Survival"));
    }

    public void setPortCheck(boolean value) {
        // TODO: What is this?
        // this.handler.sendOption("portChecking", String.valueOf(value));
    }

    public void handleOption(String name, String value) {
        if ("bandwidth".equals(name)) {
            String[] v = value.split(";");
            this.network.addStatistics(Double.valueOf(v[0]), Double.valueOf(v[1]));
        }
    }

    @Override
    public Integer putPacket(Player player, DataPacket packet) {
        return this.putPacket(player, packet, false);
    }

    @Override
    public Integer putPacket(Player player, DataPacket packet, boolean needACK) {
        return this.putPacket(player, packet, needACK, false);
    }

    @Override
    public Integer putPacket(Player player, DataPacket packet, boolean needACK, boolean immediate) {
        if (this.identifiers.containsKey(player.rawHashCode())) {
            if (!packet.isEncoded) {
                packet.encode();
            }
            RakNetClientSession session = raknet.getSession(player.globalRakNetId);
            RakNetPacket wrapper  = new RakNetPacket(0xFE); // RakNetPacket will automatically write the ID byte you give to it
            wrapper.write(packet.getBuffer());
            session.sendMessage(Reliability.RELIABLE_ORDERED, wrapper);

            // TODO: Fix ACK
            return 0;
        }

        return null;

    }

    private DataPacket getPacket(byte[] buffer) {
        byte pid = buffer[0];
        int start = 1;

        if (pid == (byte) 0xfe) {
            pid = buffer[1];
            start++;
        }
        DataPacket data = this.network.getPacket(pid);

        if (data == null) {
            return null;
        }

        data.setBuffer(buffer, start);

        return data;
    }
}
```

**Comment by whirvis** [comment]
Your code is out of date, you should be getting errors. For example, I renamed the handlePacket() method to handleMessage() to make it more consistent with the rest of the API. Are you using an IDE atm?

**Comment by MrPowerGamerBR** [comment]
@MarfGamer yeah... just imagine that the code was right (I forgot that I did use ```git reset --hard``` to revert the changes I made)

Let me get the updated code.

**Comment by whirvis** [comment]
Ok. Get the updated code and make sure it works :)

**Comment by MrPowerGamerBR** [comment]
@MarfGamer done

```
package cn.nukkit.network;

import cn.nukkit.Nukkit;
import cn.nukkit.Player;
import cn.nukkit.Server;
import cn.nukkit.event.player.PlayerCreationEvent;
import cn.nukkit.event.server.QueryRegenerateEvent;
import cn.nukkit.network.protocol.DataPacket;
import cn.nukkit.network.protocol.ProtocolInfo;
import cn.nukkit.raknet.protocol.EncapsulatedPacket;
import cn.nukkit.utils.Binary;
import cn.nukkit.utils.MainLogger;
import io.netty.buffer.ByteBuf;
import net.marfgamer.jraknet.RakNetPacket;
import net.marfgamer.jraknet.identifier.MCPEIdentifier;
import net.marfgamer.jraknet.protocol.Reliability;
import net.marfgamer.jraknet.server.RakNetServer;
import net.marfgamer.jraknet.server.RakNetServerListener;
import net.marfgamer.jraknet.session.RakNetClientSession;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.UnknownHostException;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * author: MagicDroidX
 * Nukkit Project
 */
public class RakNetInterface implements AdvancedSourceInterface {

    private final Server server;

    private Network network;

    private final RakNetServer raknet;

    private final Map<String, Player> players = new ConcurrentHashMap<>();

    private final Map<Integer, String> identifiers = new ConcurrentHashMap<>();

    private final Map<String, Integer> identifiersACK = new ConcurrentHashMap<>();

    private int[] channelCounts = new int[256];

    public RakNetInterface(Server server) {
        this.server = server;

        raknet = new RakNetServer(server.getPort(), server.getMaxPlayers(), new MCPEIdentifier(server.getMotd(), ProtocolInfo.CURRENT_PROTOCOL, ProtocolInfo.MINECRAFT_VERSION_NETWORK, server.getOnlinePlayers().size(),
                server.getMaxPlayers(), server.getServerUniqueId().getMostSignificantBits() & Long.MAX_VALUE, "New World", "Survival"));
        raknet.setListener(new RakNetServerListener() {
            // Client connected
            @Override
            public void onClientConnect(RakNetClientSession session) {
                openSession(String.valueOf(session.getGloballyUniqueId()), session.getAddress().getHostString(), session.getInetPort(), session.getGloballyUniqueId());
            }

            // Client disconnected
            @Override
            public void onClientDisconnect(RakNetClientSession session, String reason) {
                // We first check if the global ID exists (prevents NPE when shutting down the server)
                if (players.containsKey(String.valueOf(session.getGloballyUniqueId()))) {
                    close(players.get(String.valueOf(session.getGloballyUniqueId())), reason);
                }
            }

            // Packet received
            @Override
            public void handleMessage(RakNetClientSession session, RakNetPacket packet, int channel) {
                handleRakNetPacket(session.getGloballyUniqueId(), packet);
            }
            
            // UT3 server query
            @Override
            public void handleNettyMessage(ByteBuf buf, InetSocketAddress address) {
                System.out.println("Received Netty message!");
            }
        });

        // Start server
        raknet.startThreaded();
    }

    @Override
    public void setNetwork(Network network) {
        this.network = network;
    }

    @Override
    public boolean process() {
        boolean work = false;
        return work;
    }

    public void closeSession(String identifier, String reason) {
        if (this.players.containsKey(identifier)) {
            Player player = this.players.get(identifier);
            this.identifiers.remove(player.rawHashCode());
            this.players.remove(identifier);
            this.identifiersACK.remove(identifier);
            player.close(player.getLeaveMessage(), reason);
        }
    }

    @Override
    public long getNetworkLatency(Player player) {
        return this.raknet.getSession(player.globalRakNetId).getLatency();
    }

    @Override
    public void close(Player player) {
        this.close(player, "unknown reason");
    }

    @Override
    public void close(Player player, String reason) {
        if (this.identifiers.containsKey(player.rawHashCode())) {
            String id = this.identifiers.get(player.rawHashCode());
            // TODO: I don't know WHY they did this for no reason at all!
            // Those things will be closed in #closeSession anyway
            // this.players.remove(id);
            // this.networkLatency.remove(id);
            // this.identifiersACK.remove(id);
            this.closeSession(id, reason);
            // this.identifiers.remove(player.rawHashCode());
        }
    }

    @Override
    public void shutdown() {
        this.raknet.shutdown();
    }

    @Override
    public void emergencyShutdown() {
        // TODO: What is a "emergency shutdown"?
        this.raknet.shutdown();
    }

    public void openSession(String identifier, String address, int port, long clientID) {
        PlayerCreationEvent ev = new PlayerCreationEvent(this, Player.class, Player.class, null, address, port);
        this.server.getPluginManager().callEvent(ev);
        Class<? extends Player> clazz = ev.getPlayerClass();

        try {
            Constructor constructor = clazz.getConstructor(SourceInterface.class, Long.class, String.class, int.class);
            Player player = (Player) constructor.newInstance(this, ev.getClientId(), ev.getAddress(), ev.getPort());
            player.globalRakNetId = clientID;
            this.players.put(identifier, player);
            this.identifiersACK.put(identifier, 0);
            this.identifiers.put(player.rawHashCode(), identifier);
            this.server.addPlayer(identifier, player);
        } catch (NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            Server.getInstance().getLogger().logException(e);
        }
    }

    public void handleRakNetPacket(long identifier, RakNetPacket packet) {
        if (this.players.containsKey(String.valueOf(identifier))) {
            DataPacket pk = null;
            try {
                if (packet.array().length > 0) {
                    pk = this.getPacket(packet.array());
                    if (pk != null) {
                        pk.decode();
                        DataPacket finalPk = pk;
                        // Synchronize the data processing to the main thread
                        // *Maybe* we don't need to synchronize it, but as Nukkit isn't thread safe...
                        // better safe than sorry
                        Server.getInstance().getScheduler().scheduleTask(new Runnable() {
                            public void run() {
                                players.get(String.valueOf(identifier)).handleDataPacket(finalPk);
                            }
                        });
                    }
                }
            } catch (Exception e) {
                this.server.getLogger().logException(e);
                if (Nukkit.DEBUG > 1 && pk != null) {
                    MainLogger logger = this.server.getLogger();
                    //                    if (logger != null) {
                    logger.debug("Packet " + pk.getClass().getName() + " 0x" + Binary.bytesToHexString(packet.array()));
                    //logger.logException(e);
                    //                    }
                }

                if (this.players.containsKey(String.valueOf(identifier))) {
                    try {
                        this.raknet.blockAddress(InetAddress.getByName(this.players.get(identifier).getAddress()), 5);
                    } catch (UnknownHostException e1) {
                        e1.printStackTrace();
                    }
                }
            }
        }
    }

    public void handleEncapsulated(String identifier, EncapsulatedPacket packet, int flags) {
        throw new RuntimeException();
    }

    @Override
    public void blockAddress(String address) {
        this.blockAddress(address, 300);
    }

    @Override
    public void blockAddress(String address, int timeout) {
        try {
            this.raknet.blockAddress(InetAddress.getByName(address), timeout);
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }
    }

    public void handleRaw(String address, int port, byte[] payload) {
        this.server.handlePacket(address, port, payload);
    }

    @Override
    public void sendRawPacket(String address, int port, byte[] payload) {
        byte[] buffer = Binary.appendBytes(
                new byte[]{(byte) (address.length() & 0xff)},
                address.getBytes(StandardCharsets.UTF_8),
                Binary.writeShort(port),
                payload
                );
        RakNetPacket pk = new RakNetPacket(0x8);
        pk.write(buffer);
        // raknet.sendRawMessage(pk, InetSocketAddress.createUnresolved(address, port)); // Sends the raw bytes from the packet to the specified address
    }

    public void notifyACK(String identifier, int identifierACK) {
        // TODO: Better ACK notification implementation!
        for (Player p : server.getOnlinePlayers().values()) {
            p.notifyACK(identifierACK);
        }
    }

    @Override
    public void setName(String name) {
        QueryRegenerateEvent info = this.server.getQueryInformation();

        raknet.setIdentifier(new MCPEIdentifier(server.getMotd(), ProtocolInfo.CURRENT_PROTOCOL, ProtocolInfo.MINECRAFT_VERSION_NETWORK, info.getPlayerCount(),
                info.getMaxPlayerCount(), server.getServerUniqueId().getMostSignificantBits() & Long.MAX_VALUE, "New World", "Survival"));
    }

    public void setPortCheck(boolean value) {
        // TODO: What is this?
        // this.handler.sendOption("portChecking", String.valueOf(value));
    }

    public void handleOption(String name, String value) {
        if ("bandwidth".equals(name)) {
            String[] v = value.split(";");
            this.network.addStatistics(Double.valueOf(v[0]), Double.valueOf(v[1]));
        }
    }

    @Override
    public Integer putPacket(Player player, DataPacket packet) {
        return this.putPacket(player, packet, false);
    }

    @Override
    public Integer putPacket(Player player, DataPacket packet, boolean needACK) {
        return this.putPacket(player, packet, needACK, false);
    }

    @Override
    public Integer putPacket(Player player, DataPacket packet, boolean needACK, boolean immediate) {
        if (this.identifiers.containsKey(player.rawHashCode())) {
            if (!packet.isEncoded) {
                packet.encode();
            }
            RakNetClientSession session = raknet.getSession(player.globalRakNetId);
            RakNetPacket wrapper  = new RakNetPacket(0xFE); // RakNetPacket will automatically write the ID byte you give to it
            wrapper.write(packet.getBuffer());
            session.sendMessage(Reliability.RELIABLE_ORDERED, wrapper);

            // TODO: Fix ACK
            return 0;
        }

        return null;

    }

    private DataPacket getPacket(byte[] buffer) {
        byte pid = buffer[0];
        int start = 1;

        if (pid == (byte) 0xfe) {
            pid = buffer[1];
            start++;
        }
        DataPacket data = this.network.getPacket(pid);

        if (data == null) {
            return null;
        }

        data.setBuffer(buffer, start);

        return data;
    }
}
```

And now I tested it and the server works... but the message is never shown in the console.

**Comment by MrPowerGamerBR** [comment]
@MarfGamer also, to be 100% sure, that message should be shown when the server receives any packet, right?

**Comment by whirvis** [comment]
Yes. I found the issue :) I will push once again on the same version (Sorry :/) Your code was correct but I was calling the method incorrectly.

**Comment by whirvis** [comment]
The new build has been successfully pushed! This should be the last time that you have to remove the rouge jar and restart eclipse :)

**Comment by MrPowerGamerBR** [comment]
@MarfGamer now it is fixed 👍

**Comment by whirvis** [comment]
Alright! Glad to hear :D
